<template>
  <div class="workbench-view">
    <div class="history-page">
      <section class="history-hero"><div><span class="kicker">每次创作都留下轨迹</span><h2>找到上次停下的位置</h2><p>历史记录不会把失败刷新成空白。状态、费用和成果都来自本地回执，方便你继续修改或重新交付。</p></div><div class="hero-actions"><el-button type="primary" @click="$router.push('/free-create')">手动创作</el-button><el-button plain @click="$router.push('/batch')">批量生成</el-button></div></section>
      <section class="panel"><header class="panel-heading"><div><span class="kicker">CODEX TASKS</span><h3>编排任务</h3></div><span class="count">{{ sessions.length }}</span></header><div v-if="sessions.length" class="task-list"><article v-for="item in sessions" :key="item.id" class="task-row"><div class="task-main"><span :class="['dot', statusTone(item.status)]"></span><div><strong>{{ item.title || '未命名任务' }}</strong><p>{{ item.user_goal || '没有记录目标描述' }}</p><small>{{ formatDate(item.updated_at) }}</small></div></div><div class="task-status" :class="statusTone(item.status)">{{ statusLabel(item.status) }}</div><div class="task-meta"><span>{{ item.status === 'succeeded' ? '已完成' : '可继续处理' }}</span><el-button size="small" plain @click="$router.push('/codex-console/' + item.id)">打开任务</el-button></div></article></div><div v-else class="empty">还没有编排任务。你可以先从一句话开始。</div></section>
      <section class="panel"><header class="panel-heading"><div><span class="kicker">BATCH QUEUE</span><h3>手动与批量创作</h3></div><span class="count">{{ batches.length }}</span></header><div v-if="batches.length" class="batch-list"><article v-for="item in batches" :key="item.id" class="batch-row"><div><strong>{{ item.title }}</strong><p>{{ item.settings?._origin === 'manual' ? '手动创作' : item.kind === 'image' ? '批量图片' : '批量视频' }} · {{ item.total }} 项 · 并发 {{ item.concurrency }}</p></div><div class="batch-progress"><el-progress :percentage="batchPercent(item)" :show-text="false" /><small>{{ item.completed }} 完成 · {{ item.failed }} 失败 · {{ batchLabel(item.status) }}</small></div><el-button size="small" plain @click="$router.push(item.settings?._origin === 'manual' ? '/free-create' : '/batch?batch=' + item.id)">查看任务</el-button></article></div><div v-else class="empty">还没有批量批次。</div></section>
    </div>
  </div>
</template>
<script setup>
import { onMounted, ref } from 'vue'
import { useWorkbenchPage } from '@/composables/useWorkbenchPage'
import orchestrationAPI from '@/api/orchestration'
import mediaBatchAPI from '@/api/mediaBatch'
const sessions = ref([]); const batches = ref([]); const loading = ref(false); const error = ref('')
function statusLabel(s) { return ({ running: '执行中', planned: '待开始', waiting_confirmation: '待确认', paused: '已暂停', succeeded: '已完成', partial: '部分完成', failed: '失败', cancelled: '已取消' })[s] || '待处理' }
function statusTone(s) { return ['succeeded'].includes(s) ? 'success' : ['failed','cancelled'].includes(s) ? 'danger' : ['paused','planned','waiting_confirmation','partial'].includes(s) ? 'warning' : ['running'].includes(s) ? 'active' : 'muted' }
function batchLabel(s) { return ({ queued: '准备中', running: '执行中', paused: '已暂停', completed: '已完成', partial: '部分完成', failed: '失败' })[s] || '处理中' }
function batchPercent(item) { return item.total ? Math.round((item.completed + item.failed) / item.total * 100) : 0 }
function formatDate(value) { return value ? new Date(value).toLocaleString('zh-CN') : '时间未知' }
async function load() { loading.value = true; error.value = ''; try { const [taskResult, batchResult] = await Promise.all([orchestrationAPI.sessions({ limit: 100 }), mediaBatchAPI.list({ limit: 100 })]); sessions.value = taskResult?.items || []; batches.value = batchResult?.items || [] } catch (e) { error.value = e?.message || '暂时无法读取历史记录' } finally { loading.value = false } }
onMounted(load)
useWorkbenchPage({ refresh: load, error: () => error.value, loading: () => loading.value })
</script>
<style scoped>
.history-page{display:grid;gap:18px}.history-hero{display:flex;justify-content:space-between;align-items:center;gap:24px;padding:25px 29px;border:1px solid var(--border-color);background:linear-gradient(110deg,var(--bg-card),var(--bg-card))}.kicker{color:var(--ui-accent);font-size:12px;letter-spacing:.12em}.history-hero h2{margin:9px 0 7px;font-size:28px}.history-hero p{max-width:760px;margin:0;color:var(--text-muted);font-size:13px;line-height:1.7}.hero-actions{display:flex;gap:8px;flex-wrap:wrap}.panel{padding:19px;border:1px solid var(--border-color);background:var(--bg-card)}.panel-heading{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;margin-bottom:14px}.panel-heading h3{margin:5px 0 0;font-size:17px}.count{color:var(--ui-accent);font-size:22px}.task-list,.batch-list{display:grid}.task-row,.batch-row{display:grid;grid-template-columns:minmax(0,1.5fr) 100px minmax(200px,.8fr);gap:16px;align-items:center;padding:14px 0;border-top:1px solid var(--border-color)}.task-main{display:flex;gap:10px;min-width:0}.task-main>div{min-width:0}.dot{width:8px;height:8px;margin-top:5px;border-radius:50%;background:var(--bg-card)}.dot.success{background:var(--ui-accent)}.dot.active{background:var(--ui-accent);box-shadow:0 0 0 4px #62ddbd22}.dot.warning{background:var(--bg-card)}.dot.danger{background:var(--bg-card)}.task-main strong,.task-main p,.task-main small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.task-main strong{color:var(--text-primary);font-size:13px}.task-main p{margin:4px 0;color:var(--text-muted);font-size:12px}.task-main small{color:var(--text-muted);font-size:11px}.task-status{font-size:12px}.task-status.success{color:var(--ui-accent)}.task-status.active{color:var(--ui-accent)}.task-status.warning{color:var(--ui-warning)}.task-status.danger{color:var(--ui-danger)}.task-meta{display:flex;justify-content:flex-end;align-items:center;gap:10px;color:var(--text-muted);font-size:12px}.batch-row{grid-template-columns:minmax(0,1fr) minmax(180px,.7fr) auto}.batch-row strong{color:var(--text-primary);font-size:12px}.batch-row p{margin:5px 0 0;color:var(--text-muted);font-size:12px}.batch-progress small{display:block;margin-top:6px;color:var(--text-muted);font-size:11px}.empty{padding:45px;text-align:center;color:var(--text-muted);font-size:12px}@media(max-width:780px){.history-hero{flex-direction:column;align-items:flex-start}.task-row,.batch-row{grid-template-columns:1fr;gap:8px}.task-meta{justify-content:flex-start}}
</style>
