const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { spawn } = require('node:child_process');

const fail = (code, message) => Object.assign(new Error(message), { code });

function existing(file) {
  try { return fs.statSync(file).isFile() ? file : null; } catch { return null; }
}

function findExecutable(env = process.env, platform = process.platform) {
  const configured = env.YINZI_AFTERFX_PATH || env.AFTERFX_PATH;
  if (configured) return existing(configured);
  if (platform === 'win32') {
    const root = path.join(env.ProgramFiles || 'C:/Program Files', 'Adobe');
    try {
      return fs.readdirSync(root).filter(name => /^Adobe After Effects(?: |$)/i.test(name))
        .sort((a, b) => b.localeCompare(a, 'en', { numeric: true }))
        .map(name => existing(path.join(root, name, 'Support Files', 'AfterFX.exe'))).find(Boolean) || null;
    } catch { return null; }
  }
  return null;
}

function escapeJs(value) {
  return JSON.stringify(String(value)).slice(1, -1).replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
}

// An engineering fixture; the production showcase uses its own shot plan and assets.
function buildDemoScript({ outputDir, title = 'AI × After Effects', duration = 8, width = 1920, height = 1080 } = {}) {
  if (!outputDir) throw new Error('outputDir is required');
  for (const [name, value, min, max] of [['width',width,64,4096],['height',height,64,4096],['duration',duration,2,30]]) {
    if (!Number.isFinite(value) || value < min || value > max || (name !== 'duration' && !Number.isInteger(value))) throw fail('INVALID_AE_PARAMETER', name + ' is out of range');
  }
  if (typeof title !== 'string' || title.length > 200) throw fail('INVALID_AE_PARAMETER', 'title must be at most 200 characters');
  const out = path.resolve(outputDir);
  const seconds = Math.max(2, Math.min(30, Number(duration) || 8));
  return `/* Yinzi AI AE demo; generated by afterEffectsBridge */
(function(){
  var undo = false;
  function receipt(text) { var f = new File("${escapeJs(out)}/yinzi-ai-ae-demo.receipt.json"); f.encoding='UTF-8'; if (!f.open('w')) throw new Error('Cannot open receipt'); f.write(text); f.close(); }
  try {
  var root = new Folder("${escapeJs(out)}"); if (!root.exists) root.create();
  if (new File(root.fsName+'/yinzi-ai-ae-demo.aep').exists || new File(root.fsName+'/yinzi-ai-ae-demo.avi').exists) throw new Error('Output exists; use a new directory');
  if (app.project && (app.project.numItems > 0 || app.project.file || app.project.dirty)) throw new Error('AE_PROJECT_BUSY: preserve the current project and use an empty editor');
  var project = app.project || app.newProject();
  if (!project) throw new Error('No empty project');
  app.beginUndoGroup("Yinzi AI Demo"); undo = true;
  var comp = project.items.addComp("YINZI_AI_AE_DEMO", ${width}, ${height}, 1, ${seconds}, 30);
  comp.layers.addSolid([0.015,0.02,0.05], 'Backdrop', ${width}, ${height}, 1, ${seconds});
  function rect(name, color, pos, scale, opacity){
    var l=comp.layers.addShape(); l.name=name; var c=l.property("ADBE Root Vectors Group");
    var g=c.addProperty("ADBE Vector Shape - Rect"); g.property("ADBE Vector Rect Size").setValue([${width*.4},${height*.4}]);
    var f=c.addProperty("ADBE Vector Graphic - Fill"); f.property("ADBE Vector Fill Color").setValue(color);
    l.property("ADBE Transform Group").property("ADBE Position").setValue(pos);
    l.property("ADBE Transform Group").property("ADBE Scale").setValue([scale,scale]);
    l.property("ADBE Transform Group").property("ADBE Opacity").setValueAtTime(0,0);
    l.property("ADBE Transform Group").property("ADBE Opacity").setValueAtTime(0.55,opacity);
    l.property("ADBE Transform Group").property("ADBE Opacity").setValueAtTime(${seconds}-0.45,opacity);
    l.property("ADBE Transform Group").property("ADBE Opacity").setValueAtTime(${seconds},0); return l;
  }
  var a=rect("Cyan layer",[0.02,0.75,0.95],[${width/2},${height/2}],100,82);
  var b=rect("Magenta layer",[0.85,0.08,0.55],[${width/2},${height/2}],72,72);
  b.property("ADBE Transform Group").property("ADBE Rotate Z").setValueAtTime(0,-12);
  b.property("ADBE Transform Group").property("ADBE Rotate Z").setValueAtTime(${seconds}/2,12);
  b.property("ADBE Transform Group").property("ADBE Rotate Z").setValueAtTime(${seconds},-12);
  a.property("ADBE Transform Group").property("ADBE Position").setValueAtTime(0,[${width*.35},${height*.5}]);
  a.property("ADBE Transform Group").property("ADBE Position").setValueAtTime(${seconds},[${width*.65},${height*.5}]);
  var mask = a.property('ADBE Mask Parade').addProperty('ADBE Mask Atom');
  var shape = new Shape(); shape.vertices=[[-${width*.2},-${height*.2}],[${width*.2},-${height*.2}],[${width*.2},${height*.2}],[-${width*.2},${height*.2}]];
  shape.inTangents=[[0,0],[0,0],[0,0],[0,0]]; shape.outTangents=[[0,0],[0,0],[0,0],[0,0]]; shape.closed=true;
  mask.property('ADBE Mask Shape').setValue(shape); mask.property('ADBE Mask Feather').setValue([12,12]);
  var t=comp.layers.addText("${escapeJs(title)}"); t.name="AI controlled typography";
  var doc = t.property('ADBE Text Properties').property('ADBE Text Document'), style = doc.value;
  style.fontSize=${Math.round(height*.06)}; style.fillColor=[1,1,1]; style.justification=ParagraphJustification.CENTER_JUSTIFY; doc.setValue(style);
  var bounds=t.sourceRectAtTime(0,false); t.property('ADBE Transform Group').property('ADBE Anchor Point').setValue([bounds.left+bounds.width/2,bounds.top+bounds.height/2]);
  t.property("ADBE Transform Group").property("ADBE Position").setValue([${width/2},${height/2}]);
  t.property("ADBE Transform Group").property("ADBE Scale").setValueAtTime(0,[35,35]);
  t.property("ADBE Transform Group").property("ADBE Scale").setValueAtTime(1.2,[100,100]);
  t.property("ADBE Transform Group").property("ADBE Scale").setValueAtTime(${seconds},[118,118]);
  t.property("ADBE Transform Group").property("ADBE Opacity").setValueAtTime(0,0);
  t.property("ADBE Transform Group").property("ADBE Opacity").setValueAtTime(1,100);
  t.property("ADBE Transform Group").property("ADBE Opacity").setValueAtTime(${seconds}-0.5,100);
  t.property("ADBE Transform Group").property("ADBE Opacity").setValueAtTime(${seconds},0);
  var rq=project.renderQueue.items.add(comp); comp.openInViewer();
  rq.outputModule(1).file=new File(root.fsName+"/yinzi-ai-ae-demo.avi");
  var f=new File(root.fsName+"/yinzi-ai-ae-demo.aep"); project.save(f);
  project.renderQueue.render();
  if (rq.status !== RQItemStatus.DONE) throw new Error('Render queue did not finish');
  project.save(f); receipt('{"status":"rendered_pending_media_qa"}');
  } catch (error) { receipt('{"status":"failed","message":'+ '"'+encodeURIComponent(String(error.message))+'"}'); }
  finally { if (undo) app.endUndoGroup(); }
})();\n`;
}

function readReceipt(dir) {
  let receipt;
  try { receipt = JSON.parse(fs.readFileSync(path.join(dir,'yinzi-ai-ae-demo.receipt.json'),'utf8').replace(/^\uFEFF/,'')); }
  catch (e) { if (e.code === 'ENOENT' || e instanceof SyntaxError) return null; throw e; }
  if (receipt.status === 'failed') throw fail('AFTERFX_SCRIPT_FAILED',decodeURIComponent(receipt.message));
  if (receipt.status !== 'rendered_pending_media_qa') throw fail('AFTERFX_RECEIPT_INVALID','Unknown AE receipt');
  for (const extension of ['aep','avi']) {
    const output = path.join(dir,'yinzi-ai-ae-demo.'+extension);
    if (!existing(output) || !fs.statSync(output).size) throw fail('AFTERFX_OUTPUT_MISSING','Missing or empty AE output');
  }
  return receipt;
}

async function runAfterEffects(scriptPath, { executable = findExecutable(), timeout = 20 * 60 * 1000 } = {}) {
  if (!Number.isFinite(timeout) || timeout <= 0) throw fail('INVALID_AE_PARAMETER','timeout must be positive');
  const script = path.resolve(scriptPath), dir = path.dirname(script);
  if (!existing(script) || path.basename(script) !== 'yinzi-ai-ae-demo.jsx') throw fail('AFTERFX_SCRIPT_MISSING','Use the script produced by createDemo');
  const prior = readReceipt(dir); if (prior) return {...prior,reused:true};
  if (!executable || !existing(executable)) throw fail('AFTERFX_MISSING','AfterFX.exe is missing; set YINZI_AFTERFX_PATH after installation');
  try { fs.writeFileSync(path.join(dir,'yinzi-ai-ae-demo.dispatch.json'),JSON.stringify({script,executable,submitted_at:new Date().toISOString()}),{flag:'wx'}); }
  catch (e) { if (e.code === 'EEXIST') throw fail('AFTERFX_ALREADY_DISPATCHED','Inspect the original editor and receipt before retrying'); throw e; }
  const child=spawn(executable,['-r',script],{cwd:dir,windowsHide:false,shell:false,stdio:'ignore'});
  let launchError; child.once('error',e=>{launchError=e;}); child.unref();
  const start=Date.now();
  while (Date.now()-start < timeout) {
    if (launchError) throw launchError;
    const result=readReceipt(dir); if (result) return {...result,executable};
    await new Promise(resolve=>setTimeout(resolve,Math.min(500,timeout)));
  }
  // AfterFX may forward -r to an existing GUI; its exit code is not a render receipt.
  throw fail('AFTERFX_RESULT_UNKNOWN','No receipt yet; the editor was preserved. Inspect the original run');
}

function createDemo(outputDir, options = {}) {
  const dir = path.resolve(outputDir); fs.mkdirSync(dir, { recursive: true });
  const scriptPath = path.join(dir, 'yinzi-ai-ae-demo.jsx');
  const script=buildDemoScript({ ...options, outputDir: dir });
  if (['jsx','aep','avi','receipt.json','dispatch.json'].some(ext=>fs.existsSync(path.join(dir,'yinzi-ai-ae-demo.'+ext)))) throw fail('AFTERFX_OUTPUT_EXISTS','Use a new directory; old output is preserved');
  fs.writeFileSync(scriptPath, script, {encoding:'utf8',flag:'wx'});
  return { scriptPath, executable: findExecutable(), outputDir: dir, platform: os.platform() };
}

module.exports = { findExecutable, buildDemoScript, runAfterEffects, createDemo, readReceipt };
