// Contracts and executors share one registry. No contract is made executable
// just because a component probe succeeded; acceptance is per operation.
const operations = [];
const {verifiedOperation}=require('./localMediaValidation');
const parameterSchemas=require('./localMediaParameterSchemas.json');
function number(p, key, fallback, min, max) { const n = p[key] == null ? fallback : Number(p[key]); if (!Number.isFinite(n) || n < min || n > max) throw new Error(`参数 ${key} 应在 ${min} 到 ${max} 之间`); return n; }
function image(id,title,apply,defaults={}) { operations.push({id:'local.image.'+id,title,kind:'image',component_id:'media.sharp',apply,defaults,source:'https://sharp.pixelplumbing.com/api-operation/'}); }
function filter(kind,id,title,build,defaults={}) { operations.push({id:`local.${kind}.${id}`,title,kind,component_id:'media.ffmpeg',build,defaults,source:'https://ffmpeg.org/ffmpeg-filters.html#'+id}); }
const n=number;
image('resize','调整图片尺寸',(s,p)=>s.resize({width:n(p,'width',96,1,8192),height:n(p,'height',64,1,8192),fit:'inside'}));
image('crop','按坐标裁剪图片',(s,p)=>s.extract({left:n(p,'left',8,0,8192),top:n(p,'top',8,0,8192),width:n(p,'width',64,1,8192),height:n(p,'height',48,1,8192)}));
image('extend','为图片补边',(s,p)=>s.extend({top:n(p,'pixels',8,0,2048),bottom:n(p,'pixels',8,0,2048),left:n(p,'pixels',8,0,2048),right:n(p,'pixels',8,0,2048),background:'#ffffff'}));
image('rotate','旋转图片',(s,p)=>s.rotate(n(p,'angle',90,-360,360)));
image('flip','垂直翻转图片',s=>s.flip());
image('flop','水平镜像图片',s=>s.flop());
image('grayscale','转换灰度图片',s=>s.grayscale());
image('negate','图片负片反色',s=>s.negate({alpha:false}));
image('blur','图片高斯模糊',(s,p)=>s.blur(n(p,'sigma',1.2,0.3,100)));
image('sharpen','增强图片细节',(s,p)=>s.sharpen({sigma:n(p,'sigma',1,0.01,10)}));
image('median','去除图片椒盐噪点',(s,p)=>s.median(n(p,'size',3,1,9)));
image('threshold','生成黑白阈值图',(s,p)=>s.threshold(n(p,'threshold',128,0,255)));
image('normalize','拉伸图片亮度范围',s=>s.normalize());
image('gamma','调整图片伽马',(s,p)=>s.gamma(n(p,'gamma',1.8,1,3)));
image('tint','为灰度层着色',s=>s.tint({r:210,g:150,b:70}));
image('modulate','调整亮度饱和度色相',(s,p)=>s.modulate({brightness:n(p,'brightness',1.1,0.1,3),saturation:n(p,'saturation',1.15,0,3),hue:n(p,'hue',15,0,360)}));
image('linear','线性曝光调整',(s,p)=>s.linear(n(p,'gain',1.1,0.1,3),n(p,'offset',3,-255,255)));
image('recomb','通道矩阵复古调色',s=>s.recomb([[0.393,0.769,0.189],[0.349,0.686,0.168],[0.272,0.534,0.131]]));
image('emboss','图片浮雕卷积',s=>s.convolve({width:3,height:3,kernel:[-2,-1,0,-1,1,1,0,1,2],offset:128}));
image('edges','图片边缘卷积',s=>s.convolve({width:3,height:3,kernel:[-1,-1,-1,-1,8,-1,-1,-1,-1],offset:128}));
image('flatten','透明图片铺白底',s=>s.flatten({background:'#ffffff'}));
image('remove-alpha','移除透明通道',s=>s.removeAlpha());
image('ensure-alpha','添加统一透明度',(s,p)=>s.ensureAlpha(n(p,'alpha',0.7,0,1)));
image('extract-alpha','导出透明通道灰度图',s=>s.ensureAlpha().extractChannel(3));
image('extract-red','导出红色通道',s=>s.extractChannel('red'));
image('srgb','标准化 sRGB 色彩空间',s=>s.toColourspace('srgb'));
image('cmyk','生成印刷 CMYK 图片',s=>s.toColourspace('cmyk').jpeg());
image('palette','生成有限调色板 PNG',(s,p)=>s.png({palette:true,colours:n(p,'colors',16,2,256),dither:0}));
image('convert','转换图片输出格式',(s,p)=>{const f=p.format||'webp';if(!['png','jpeg','webp','avif','tiff'].includes(f))throw Error('图片格式不支持');return s.toFormat(f);},{format:'webp'});
image('trim','去除统一颜色边缘',s=>s.trim({threshold:8}));
image('pixelate','像素化缩略图',(s,p)=>s.resize({width:n(p,'width',24,1,256),kernel:'nearest'}));
image('clahe','自适应局部对比度',s=>s.clahe({width:16,height:16,maxSlope:3}));
image('threshold-alpha','将黑色背景转换为透明',s=>s.unflatten());
image('affine','执行仿射倾斜变换',s=>s.affine([[1,0.15],[0,1]],{background:'#ffffff'}));
image('join-border','叠加居中边框',async(s,p)=>{const {width,height}=await s.metadata();const t=Math.min(n(p,'thickness',4,1,128),width/4,height/4);return s.composite([{input:Buffer.from(`<svg width="${width}" height="${height}"><rect x="${t/2}" y="${t/2}" width="${width-t}" height="${height-t}" fill="none" stroke="white" stroke-width="${t}"/></svg>`),gravity:'centre'}]);});
image('metadata-strip','清除输出隐私元数据',s=>s.png());
const video=(...args)=>filter('video',...args), audio=(...args)=>filter('audio',...args);
video('scale','调整视频分辨率',p=>`scale=${n(p,'width',128,16,4096)}:${n(p,'height',72,16,4096)}`);
video('crop','裁剪视频区域',p=>`crop=${n(p,'width',128,16,4096)}:${n(p,'height',72,16,4096)}:${n(p,'x',8,0,4096)}:${n(p,'y',8,0,4096)}`);
video('pad','视频扩展画布',()=> 'pad=iw+32:ih+32:16:16:black');
video('transpose','旋转视频方向',p=>`transpose=${n(p,'direction',1,0,3)}`);
video('hflip','水平镜像视频',()=> 'hflip');
video('vflip','垂直翻转视频',()=> 'vflip');
video('reverse','倒放视频片段',()=> 'reverse');
video('grayscale','视频转为黑白',()=> 'hue=s=0');
video('negate','视频负片反色',()=> 'negate');
video('eq','调整视频曝光对比度',p=>`eq=brightness=${n(p,'brightness',0.03,-1,1)}:contrast=${n(p,'contrast',1.1,0.1,3)}:saturation=${n(p,'saturation',1.1,0,3)}`);
video('hue','调整视频色相',p=>`hue=h=${n(p,'degrees',20,-180,180)}`);
video('gblur','高斯柔化视频',p=>`gblur=sigma=${n(p,'sigma',1,0.1,10)}`);
video('boxblur','快速方框模糊',()=> 'boxblur=2:1');
video('unsharp','增强视频细节',()=> 'unsharp=5:5:0.5:5:5:0');
video('hqdn3d','时空联合视频降噪',()=> 'hqdn3d=2:1.5:3:2');
video('nlmeans','非局部均值视频降噪',()=> 'nlmeans=s=1:p=3:r=5');
video('deflicker','缓解亮度闪烁',()=> 'deflicker=size=3');
video('bwdif','视频去隔行',()=> 'bwdif=mode=send_frame');
video('vignette','增加视频暗角',()=> 'vignette=PI/5');
video('lenscorrection','校正镜头径向畸变',p=>`lenscorrection=k1=${n(p,'k1',-0.05,-0.5,0.5)}:k2=0`);
video('chromakey','绿幕抠像并铺黑底',()=> 'chromakey=0x00ff00:0.12:0.05,premultiply=inplace=1,format=yuv420p');
video('drawbox','叠加指定区域标记',()=> 'drawbox=x=10:y=10:w=40:h=30:color=red@0.7:t=3');
video('edgedetect','视频线稿滤镜',()=> 'edgedetect=low=0.1:high=0.4');
video('sobel','视频索贝尔边缘',()=> 'sobel=scale=1:delta=0');
video('posterize','视频分层调色风格',()=> "lutrgb=r='floor(val/32)*32':g='floor(val/32)*32':b='floor(val/32)*32'");
video('fade-in','视频淡入',p=>`fade=t=in:st=0:d=${n(p,'duration',0.3,0.01,60)}`);
video('fade-out','视频淡出',p=>`fade=t=out:st=${n(p,'start',0.4,0,86400)}:d=${n(p,'duration',0.3,0.01,60)}`);
video('fps','转换视频帧率',p=>`fps=${n(p,'fps',12,1,120)}`);
video('tmix','多帧混合柔化运动',()=> 'tmix=frames=3:weights=1 1 1');
video('minterpolate','混帧插值补帧',p=>`minterpolate=fps=${n(p,'fps',24,1,60)}:mi_mode=blend`);
video('speed','改变视频速度并同步音频',p=>`setpts=PTS/${n(p,'speed',1.5,0.5,2)}`);
video('trim','截取视频时间片段',p=>`trim=start=${n(p,'start',0.1,0,86400)}:duration=${n(p,'duration',0.4,0.01,86400)},setpts=PTS-STARTPTS`);
video('tpad','延长尾帧停留时间',p=>`tpad=stop_mode=clone:stop_duration=${n(p,'duration',0.2,0,60)}`);
video('tile','生成视频联系表',()=> 'fps=4,scale=80:48,tile=2x2',{});
video('colorbalance','视频阴影高光调色',()=> 'colorbalance=rs=0.05:bs=-0.03:rh=0.03');
video('colorchannelmixer','视频复古通道调色',()=> 'colorchannelmixer=.393:.769:.189:0:.349:.686:.168:0:.272:.534:.131');
video('curves','视频曲线提升中间调',()=> "curves=master='0/0 0.5/0.6 1/1'");
video('deband','缓解视频色带',()=> 'deband=1thr=0.02:2thr=0.02:3thr=0.02:4thr=0.02');
video('deblock','降低块状压缩伪影',()=> 'deblock=filter=weak:block=8');
video('dejudder','减轻重复帧不均匀顿挫',()=> 'dejudder=cycle=4');
video('deshake','轻微手持画面稳定',()=> 'deshake=rx=16:ry=16');
video('pixelate','视频像素化风格',()=> 'scale=max(2\\,trunc(iw/8/2)*2):max(2\\,trunc(ih/8/2)*2),scale=iw*8:ih*8:flags=neighbor');
video('lagfun','视频运动残影',()=> 'lagfun=decay=0.9');
video('noise','添加影片颗粒',p=>`noise=alls=${n(p,'amount',5,0,30)}:allf=t+u`);
video('setsar','校正像素宽高比',()=> 'setsar=1');
video('setdar','设置显示宽高比',()=> 'setdar=16/9');
video('colorlevels','调整视频黑白场',()=> 'colorlevels=rimin=0.02:gimin=0.02:bimin=0.02');
video('lut-yuv','限定视频亮度范围',()=> "lutyuv=y='clip(val,16,235)'");
audio('volume','调整音频音量',p=>`volume=${n(p,'gain',0.8,0,4)}`);
audio('loudnorm','广播响度归一化',()=> 'loudnorm=I=-16:TP=-1.5:LRA=11');
audio('alimiter','限制音频峰值',()=> 'alimiter=limit=0.9');
audio('acompressor','动态压缩音频',()=> 'acompressor=threshold=0.1:ratio=3');
audio('compand','扩展音频动态范围',()=> 'compand=attacks=0.01:decays=0.1:points=-80/-90|-40/-50|0/0');
audio('agate','音频噪声门',()=> 'agate=threshold=0.02:ratio=2');
audio('highpass','音频高通除低频',p=>`highpass=f=${n(p,'frequency',80,10,10000)}`);
audio('lowpass','音频低通削高频',p=>`lowpass=f=${n(p,'frequency',8000,100,20000)}`);
audio('bandpass','保留指定频带',()=> 'bandpass=f=1000:width_type=h:w=1000');
audio('bandreject','削除指定频带',()=> 'bandreject=f=1000:width_type=h:w=200');
audio('bass','调整低音',p=>`bass=g=${n(p,'gain',3,-20,20)}`);
audio('treble','调整高音',p=>`treble=g=${n(p,'gain',2,-20,20)}`);
audio('equalizer','参数均衡器',()=> 'equalizer=f=1000:t=q:w=1:g=3');
audio('aecho','添加回声',()=> 'aecho=0.8:0.9:60:0.2');
audio('chorus','添加合唱效果',()=> 'chorus=0.5:0.9:50:0.2:0.3:2');
audio('flanger','添加镶边效果',()=> 'flanger=delay=2:depth=2');
audio('aphaser','添加相位效果',()=> 'aphaser=in_gain=0.4');
audio('tremolo','添加振幅颤音',()=> 'tremolo=f=5:d=0.4');
audio('vibrato','添加音高颤音',()=> 'vibrato=f=5:d=0.3');
audio('pitch','改变音高并补偿时长',p=>`aresample=48000,asetrate=48000*${n(p,'factor',1.1,0.5,2)},aresample=48000,atempo=${1/n(p,'factor',1.1,0.5,2)}`);
audio('atempo','改变音频速度保持音高',p=>`atempo=${n(p,'speed',1.2,0.5,2)}`);
audio('areverse','倒放音频',()=> 'areverse');
audio('fade-in','音频淡入',()=> 'afade=t=in:d=0.2');
audio('fade-out','音频淡出',()=> 'afade=t=out:st=0.4:d=0.3');
audio('atrim','截取音频时间片段',p=>`atrim=start=${n(p,'start',0.1,0,86400)}:duration=${n(p,'duration',0.4,0.01,86400)},asetpts=PTS-STARTPTS`);
audio('adelay','添加声道延迟',()=> 'adelay=100:all=1');
audio('apad','音频尾部补静音',()=> 'apad=pad_dur=0.2');
audio('silenceremove','去除音频头部静音',()=> 'silenceremove=start_periods=1:start_duration=0.02:start_threshold=-50dB');
audio('afftdn','频谱音频降噪',()=> 'afftdn=nf=-25');
audio('adeclick','修复音频脉冲杂点',()=> 'adeclick');
audio('adeclip','修复音频削波',()=> 'adeclip');
audio('dcshift','调整音频直流偏移',()=> 'dcshift=shift=0.01');
audio('dynaudnorm','动态音量归一化',()=> 'dynaudnorm=f=100:g=3');
audio('stereo','转换双声道音频',()=> 'aformat=channel_layouts=stereo');
audio('mono','将双声道混合为单声道',()=> 'aformat=channel_layouts=mono');
audio('resample','重采样音频',p=>`aresample=${n(p,'sample_rate',44100,8000,96000)}`);
audio('asetrate','修改采样率与播放节奏',()=> 'asetrate=44100');
audio('anull','音频无损解码导出',()=> 'anull');
audio('asubboost','增强超低频',()=> 'asubboost=dry=0.8:wet=0.2');
audio('crossfeed','耳机跨声道混合',()=> 'aformat=channel_layouts=stereo,crossfeed=strength=0.3');
function getOperation(id) { return operations.find(o=>o.id===id); }
function contracts() { return operations.map(o=>({module_id:o.id,title:o.title,description:o.title,description_zh:o.title,version:1,version_track:'V5',phase:'edit',executor:'local',availability:'bridge',component_id:o.component_id,auto_install:true,
  validation_status:verifiedOperation(o.id)?'verified_windows_fixture':'execution_receipt_required',source_refs:[o.source],inputs:['input_path','parameters'],outputs:['derived_media','execution_receipt'],parameters:o.defaults,parameter_schema:parameterSchemas[o.id],
  side_effects:{network:true,filesystem_write:true,database_write:true,external_write:false,paid:false},recovery:'复用同一请求键和原素材；缺组件自动准备；失败只恢复此作业，不重建成功素材'})); }
module.exports={operations,getOperation,contracts};
