// Contracts and executors share one registry. No contract is made executable
// just because a component probe succeeded; acceptance is per operation.
const operations = [];
const {verifiedOperation}=require('./localMediaValidation');
const parameterSchemas=require('./localMediaParameterSchemas.json');
function number(p, key, fallback, min, max) { const n = p[key] == null ? fallback : Number(p[key]); if (!Number.isFinite(n) || n < min || n > max) throw new Error(`参数 ${key} 应在 ${min} 到 ${max} 之间`); return n; }
function image(id,title,apply,defaults={}) { const op={id:'local.image.'+id,title,kind:'image',component_id:'media.sharp',apply,defaults,source:'https://sharp.pixelplumbing.com/api-operation/'}; operations.push(op); return op; }
function filter(kind,id,title,build,defaults={}) { operations.push({id:`local.${kind}.${id}`,title,kind,component_id:'media.ffmpeg',build,defaults,source:'https://ffmpeg.org/ffmpeg-filters.html#'+id}); }
const n=number;
function resizeBounds(p) {
  if (p.width == null && p.height == null) return {width:96,height:64};
  return {
    width:p.width == null ? undefined : n(p,'width',undefined,1,8192),
    height:p.height == null ? undefined : n(p,'height',undefined,1,8192),
  };
}
image('resize','调整图片尺寸',(s,p)=>s.resize({...resizeBounds(p),fit:'inside'})).validateResult = ({before,after},p) => {
  const bounds=resizeBounds(p);
  const scale=Math.min(bounds.width == null ? Infinity : bounds.width/before.width, bounds.height == null ? Infinity : bounds.height/before.height);
  const expected={width:Math.max(1,Math.round(before.width*scale)),height:Math.max(1,Math.round(before.height*scale))};
  if (after.width !== expected.width || after.height !== expected.height) {
    throw Object.assign(Error(`图片尺寸不符合请求：预期 ${expected.width}x${expected.height}，实际 ${after.width}x${after.height}`),{code:'OUTPUT_DIMENSIONS_MISMATCH'});
  }
};
image('crop','按坐标裁剪图片',(s,p)=>s.extract({left:n(p,'left',8,0,8192),top:n(p,'top',8,0,8192),width:n(p,'width',64,1,8192),height:n(p,'height',48,1,8192)}));
image('extend','为图片补边',(s,p)=>s.extend({top:n(p,'pixels',8,0,2048),bottom:n(p,'pixels',8,0,2048),left:n(p,'pixels',8,0,2048),right:n(p,'pixels',8,0,2048),background:'#ffffff'}));
image('rotate','旋转图片',(s,p)=>s.rotate(n(p,'angle',90,-360,360)));
image('flip','垂直翻转图片',s=>s.flip());
image('flop','水平镜像图片',s=>s.flop());
image('grayscale','转换灰度图片',s=>s.grayscale());
image('negate','图片负片反色',s=>s.negate({alpha:false}));
image('blur','图片高斯模糊',(s,p)=>s.blur(n(p,'sigma',1.2,0.3,100)));
image('sharpen','增强图片细节',(s,p)=>s.sharpen({sigma:n(p,'sigma',1,0.01,10)}));
image('median','去除图片椒盐噪点',(s,p)=>s.median(n(p,'size',3,1,9)));
image('threshold','生成黑白阈值图',(s,p)=>s.threshold(n(p,'threshold',128,0,255)));
image('normalize','拉伸图片亮度范围',s=>s.normalize());
image('gamma','调整图片伽马',(s,p)=>s.gamma(n(p,'gamma',1.8,1,3)));
image('tint','为灰度层着色',s=>s.tint({r:210,g:150,b:70}));
image('modulate','调整亮度饱和度色相',(s,p)=>s.modulate({brightness:n(p,'brightness',1.1,0.1,3),saturation:n(p,'saturation',1.15,0,3),hue:n(p,'hue',15,0,360)}));
image('linear','线性曝光调整',(s,p)=>s.linear(n(p,'gain',1.1,0.1,3),n(p,'offset',3,-255,255)));
image('recomb','通道矩阵复古调色',s=>s.recomb([[0.393,0.769,0.189],[0.349,0.686,0.168],[0.272,0.534,0.131]]));
image('emboss','图片浮雕卷积',s=>s.convolve({width:3,height:3,kernel:[-2,-1,0,-1,1,1,0,1,2],offset:128}));
image('edges','图片边缘卷积',s=>s.convolve({width:3,height:3,kernel:[-1,-1,-1,-1,8,-1,-1,-1,-1],offset:128}));
image('flatten','透明图片铺白底',s=>s.flatten({background:'#ffffff'}));
image('remove-alpha','移除透明通道',s=>s.removeAlpha());
image('ensure-alpha','添加统一透明度',(s,p)=>s.ensureAlpha(n(p,'alpha',0.7,0,1)));
image('extract-alpha','导出透明通道灰度图',s=>s.ensureAlpha().extractChannel(3));
image('extract-red','导出红色通道',s=>s.extractChannel('red'));
image('srgb','标准化 sRGB 色彩空间',s=>s.toColourspace('srgb'));
image('cmyk','生成印刷 CMYK 图片',s=>s.toColourspace('cmyk').jpeg());
image('palette','生成有限调色板 PNG',(s,p)=>s.png({palette:true,colours:n(p,'colors',16,2,256),dither:0}));
image('convert','转换图片输出格式',(s,p)=>{const f=p.format||'webp';if(!['png','jpeg','webp','avif','tiff'].includes(f))throw Error('图片格式不支持');return s.toFormat(f);},{format:'webp'});
image('trim','去除统一颜色边缘',s=>s.trim({threshold:8}));
image('pixelate','像素化缩略图',(s,p)=>s.resize({width:n(p,'width',24,1,256),kernel:'nearest'}));
image('clahe','自适应局部对比度',s=>s.clahe({width:16,height:16,maxSlope:3}));
image('threshold-alpha','将黑色背景转换为透明',s=>s.unflatten());
image('affine','执行仿射倾斜变换',s=>s.affine([[1,0.15],[0,1]],{background:'#ffffff'}));
image('join-border','叠加居中边框',async(s,p)=>{const {width,height}=await s.metadata();const t=Math.min(n(p,'thickness',4,1,128),width/4,height/4);return s.composite([{input:Buffer.from(`<svg width="${width}" height="${height}"><rect x="${t/2}" y="${t/2}" width="${width-t}" height="${height-t}" fill="none" stroke="white" stroke-width="${t}"/></svg>`),gravity:'centre'}]);});
image('metadata-strip','清除输出隐私元数据',s=>s.png());
// Common delivery presets and lightweight finishing operations. Each contract
// has a distinct user-facing result and is exercised against real fixtures.
image('social-square','制作社媒 1:1 方图',(s)=>s.resize({width:1080,height:1080,fit:'cover',position:'centre'}));
image('social-portrait','制作社媒 4:5 竖图',(s)=>s.resize({width:1080,height:1350,fit:'cover',position:'centre'}));
image('social-landscape','制作社媒横图',(s)=>s.resize({width:1200,height:630,fit:'cover',position:'centre'}));
image('avatar','制作头像方图',(s)=>s.resize({width:512,height:512,fit:'cover',position:'centre'}));
image('thumbnail','制作缩略图',(s)=>s.resize({width:320,height:320,fit:'cover',position:'centre'}));
image('contain-white','完整主体白底适配',(s)=>s.resize({width:800,height:800,fit:'contain',background:'#ffffff'}));
image('contain-black','完整主体黑底适配',(s)=>s.resize({width:800,height:800,fit:'contain',background:'#000000'}));
image('contain-transparent','完整主体透明适配',(s)=>s.resize({width:800,height:800,fit:'contain',background:{r:0,g:0,b:0,alpha:0}}));
image('pad-square-white','补白边为正方形',async(s)=>{const m=await s.metadata();const size=Math.max(m.width||1,m.height||1);return s.extend({top:Math.floor((size-(m.height||size))/2),bottom:Math.ceil((size-(m.height||size))/2),left:Math.floor((size-(m.width||size))/2),right:Math.ceil((size-(m.width||size))/2),background:'#fff'});});
image('pad-square-black','补黑边为正方形',async(s)=>{const m=await s.metadata();const size=Math.max(m.width||1,m.height||1);return s.extend({top:Math.floor((size-(m.height||size))/2),bottom:Math.ceil((size-(m.height||size))/2),left:Math.floor((size-(m.width||size))/2),right:Math.ceil((size-(m.width||size))/2),background:'#000'});});
image('rotate-180','旋转 180 度',s=>s.rotate(180));
image('rotate-270','旋转 270 度',s=>s.rotate(270));
image('flip-both','垂直与水平翻转',s=>s.flip().flop());
image('ensure-rgba','统一为 RGBA 通道',s=>s.ensureAlpha().png());
image('flatten-black','透明图铺黑底',s=>s.flatten({background:'#000000'}));
image('flatten-gray','透明图铺灰底',s=>s.flatten({background:'#808080'}));
image('jpeg-quality','导出高质量 JPEG',(s,p)=>s.jpeg({quality:n(p,'quality',92,1,100)}));
image('webp-quality','导出高质量 WebP',(s,p)=>s.webp({quality:n(p,'quality',88,1,100)}));
image('png-compress','压缩 PNG 文件',(s,p)=>s.png({compressionLevel:n(p,'level',9,0,9)}));
image('border-black','叠加黑色边框',async(s,p)=>{const m=await s.metadata();const t=Math.min(n(p,'thickness',6,1,128),(m.width||256)/4,(m.height||256)/4);return s.extend({top:t,bottom:t,left:t,right:t,background:'#000'});});
image('border-white','叠加白色边框',async(s,p)=>{const m=await s.metadata();const t=Math.min(n(p,'thickness',6,1,128),(m.width||256)/4,(m.height||256)/4);return s.extend({top:t,bottom:t,left:t,right:t,background:'#fff'});});
image('watermark-corner','右下角叠加水印',async(s,p)=>{const m=await s.metadata();const text=String(p.text||'YINZI').replace(/[<&>"']/g,'');const svg=`<svg width="${m.width||512}" height="${m.height||512}"><text x="${(m.width||512)-18}" y="${(m.height||512)-18}" text-anchor="end" font-family="Arial" font-size="24" fill="white" fill-opacity=".72">${text}</text></svg>`;return s.composite([{input:Buffer.from(svg),blend:'over'}]);});
image('watermark-center','居中叠加半透明水印',async(s,p)=>{const m=await s.metadata();const text=String(p.text||'YINZI').replace(/[<&>"']/g,'');const svg=`<svg width="${m.width||512}" height="${m.height||512}"><text x="50%" y="52%" text-anchor="middle" font-family="Arial" font-size="${Math.max(20,Math.round((m.width||512)/10))}" fill="white" fill-opacity=".25">${text}</text></svg>`;return s.composite([{input:Buffer.from(svg),blend:'over'}]);});
image('label-corner','右上角添加标签',async(s,p)=>{const m=await s.metadata();const text=String(p.text||'NEW').replace(/[<&>"']/g,'');const svg=`<svg width="${m.width||512}" height="${m.height||512}"><rect x="${(m.width||512)-130}" y="18" width="112" height="38" rx="8" fill="#e53935"/><text x="${(m.width||512)-74}" y="44" text-anchor="middle" font-family="Arial" font-size="20" fill="white">${text}</text></svg>`;return s.composite([{input:Buffer.from(svg),blend:'over'}]);});
image('shadow','为主体添加柔和阴影',async(s)=>{const m=await s.metadata();const svg=`<svg width="${m.width||512}" height="${m.height||512}"><rect x="8" y="8" width="${Math.max(1,(m.width||512)-16)}" height="${Math.max(1,(m.height||512)-16)}" rx="12" fill="none" stroke="#000" stroke-opacity=".22" stroke-width="12"/></svg>`;return s.composite([{input:Buffer.from(svg),blend:'over'}]);});
image('tint-red','暖红色调',s=>s.tint({r:220,g:90,b:90}));
image('tint-blue','冷蓝色调',s=>s.tint({r:90,g:140,b:220}));
image('tint-green','清新绿色调',s=>s.tint({r:100,g:190,b:120}));
image('brightness-up','提亮图片',s=>s.modulate({brightness:1.25}));
image('brightness-down','压暗图片',s=>s.modulate({brightness:0.78}));
image('saturation-up','增强色彩饱和度',s=>s.modulate({saturation:1.45}));
image('saturation-down','降低色彩饱和度',s=>s.modulate({saturation:0.65}));
image('sharpen-strong','强力锐化图片',s=>s.sharpen({sigma:2,flat:1, jagged:2}));
image('blur-soft','柔和背景模糊',s=>s.blur(3));
image('poster-border','制作宣传图留白边',async(s)=>{const m=await s.metadata();const x=Math.max(12,Math.round(Math.min(m.width||512,m.height||512)*.06));return s.extend({top:x,bottom:x,left:x,right:x,background:'#fff'});});
const video=(...args)=>filter('video',...args), audio=(...args)=>filter('audio',...args);
video('scale','调整视频分辨率',p=>`scale=${n(p,'width',128,16,4096)}:${n(p,'height',72,16,4096)}`);
video('crop','裁剪视频区域',p=>`crop=${n(p,'width',128,16,4096)}:${n(p,'height',72,16,4096)}:${n(p,'x',8,0,4096)}:${n(p,'y',8,0,4096)}`);
video('pad','视频扩展画布',()=> 'pad=iw+32:ih+32:16:16:black');
video('transpose','旋转视频方向',p=>`transpose=${n(p,'direction',1,0,3)}`);
video('hflip','水平镜像视频',()=> 'hflip');
video('vflip','垂直翻转视频',()=> 'vflip');
video('reverse','倒放视频片段',()=> 'reverse');
video('grayscale','视频转为黑白',()=> 'hue=s=0');
video('negate','视频负片反色',()=> 'negate');
video('eq','调整视频曝光对比度',p=>`eq=brightness=${n(p,'brightness',0.03,-1,1)}:contrast=${n(p,'contrast',1.1,0.1,3)}:saturation=${n(p,'saturation',1.1,0,3)}`);
video('hue','调整视频色相',p=>`hue=h=${n(p,'degrees',20,-180,180)}`);
video('gblur','高斯柔化视频',p=>`gblur=sigma=${n(p,'sigma',1,0.1,10)}`);
video('boxblur','快速方框模糊',()=> 'boxblur=2:1');
video('unsharp','增强视频细节',()=> 'unsharp=5:5:0.5:5:5:0');
video('hqdn3d','时空联合视频降噪',()=> 'hqdn3d=2:1.5:3:2');
video('nlmeans','非局部均值视频降噪',()=> 'nlmeans=s=1:p=3:r=5');
video('deflicker','缓解亮度闪烁',()=> 'deflicker=size=3');
video('bwdif','视频去隔行',()=> 'bwdif=mode=send_frame');
video('vignette','增加视频暗角',()=> 'vignette=PI/5');
video('lenscorrection','校正镜头径向畸变',p=>`lenscorrection=k1=${n(p,'k1',-0.05,-0.5,0.5)}:k2=0`);
video('chromakey','绿幕抠像并铺黑底',()=> 'chromakey=0x00ff00:0.12:0.05,premultiply=inplace=1,format=yuv420p');
video('drawbox','叠加指定区域标记',()=> 'drawbox=x=10:y=10:w=40:h=30:color=red@0.7:t=3');
video('edgedetect','视频线稿滤镜',()=> 'edgedetect=low=0.1:high=0.4');
video('sobel','视频索贝尔边缘',()=> 'sobel=scale=1:delta=0');
video('posterize','视频分层调色风格',()=> "lutrgb=r='floor(val/32)*32':g='floor(val/32)*32':b='floor(val/32)*32'");
video('fade-in','视频淡入',p=>`fade=t=in:st=0:d=${n(p,'duration',0.3,0.01,60)}`);
video('fade-out','视频淡出',p=>`fade=t=out:st=${n(p,'start',0.4,0,86400)}:d=${n(p,'duration',0.3,0.01,60)}`);
video('fps','转换视频帧率',p=>`fps=${n(p,'fps',12,1,120)}`);
video('tmix','多帧混合柔化运动',()=> 'tmix=frames=3:weights=1 1 1');
video('minterpolate','混帧插值补帧',p=>`minterpolate=fps=${n(p,'fps',24,1,60)}:mi_mode=blend`);
video('speed','改变视频速度并同步音频',p=>`setpts=PTS/${n(p,'speed',1.5,0.5,2)}`);
video('trim','截取视频时间片段',p=>`trim=start=${n(p,'start',0.1,0,86400)}:duration=${n(p,'duration',0.4,0.01,86400)},setpts=PTS-STARTPTS`);
video('tpad','延长尾帧停留时间',p=>`tpad=stop_mode=clone:stop_duration=${n(p,'duration',0.2,0,60)}`);
video('tile','生成视频联系表',()=> 'fps=4,scale=80:48,tile=2x2',{});
video('colorbalance','视频阴影高光调色',()=> 'colorbalance=rs=0.05:bs=-0.03:rh=0.03');
video('colorchannelmixer','视频复古通道调色',()=> 'colorchannelmixer=.393:.769:.189:0:.349:.686:.168:0:.272:.534:.131');
video('curves','视频曲线提升中间调',()=> "curves=master='0/0 0.5/0.6 1/1'");
video('deband','缓解视频色带',()=> 'deband=1thr=0.02:2thr=0.02:3thr=0.02:4thr=0.02');
video('deblock','降低块状压缩伪影',()=> 'deblock=filter=weak:block=8');
video('dejudder','减轻重复帧不均匀顿挫',()=> 'dejudder=cycle=4');
video('deshake','轻微手持画面稳定',()=> 'deshake=rx=16:ry=16');
video('pixelate','视频像素化风格',()=> 'scale=max(2\\,trunc(iw/8/2)*2):max(2\\,trunc(ih/8/2)*2),scale=iw*8:ih*8:flags=neighbor');
video('lagfun','视频运动残影',()=> 'lagfun=decay=0.9');
video('noise','添加影片颗粒',p=>`noise=alls=${n(p,'amount',5,0,30)}:allf=t+u`);
video('setsar','校正像素宽高比',()=> 'setsar=1');
video('setdar','设置显示宽高比',()=> 'setdar=16/9');
video('colorlevels','调整视频黑白场',()=> 'colorlevels=rimin=0.02:gimin=0.02:bimin=0.02');
video('lut-yuv','限定视频亮度范围',()=> "lutyuv=y='clip(val,16,235)'");
video('drawgrid','视频叠加参考网格',()=> 'drawgrid=width=80:height=80:thickness=1:color=white@0.25');
video('drawtext','视频叠加文字',()=> "drawtext=text='YINZI':x=12:y=12:fontsize=24:fontcolor=white:box=1:boxcolor=black@0.35");
video('tblend','视频帧平均混合',()=> 'tblend=all_mode=average');
video('framestep','隔帧抽取视频',()=> 'framestep=step=2');
video('select-even','保留偶数帧',()=> "select='not(mod(n,2))',setpts=N/FRAME_RATE/TB");
video('tinterlace','生成交错视频效果',()=> 'tinterlace=mode=merge');
video('fieldorder','统一视频场序',()=> 'fieldorder=tff');
video('format-gray','视频输出灰度像素格式',()=> 'format=gray');
video('format-rgb','视频标准化 RGB 像素格式',()=> 'format=rgb24');
video('smartblur','视频智能柔化',()=> 'smartblur=lr=1.0:ls=-1.0:lt=1.0');
video('convolution','视频卷积锐化',()=> 'convolution=0 -1 0 -1 5 -1 0 -1 0');
video('kirsch','视频 Kirsch 线稿',()=> 'kirsch=planes=1');
video('roberts','视频 Roberts 边缘',()=> 'roberts=planes=1');
video('showinfo','写入视频帧信息检查',()=> 'showinfo');
video('settb','统一视频时间基',()=> 'settb=AVTB');
video('setpts-start','从零开始视频时间戳',()=> 'setpts=PTS-STARTPTS');
video('fps-24','交付 24fps 视频',()=> 'fps=24');
video('fps-30','交付 30fps 视频',()=> 'fps=30');
video('half-size','生成一半尺寸预览',()=> 'scale=iw/2:ih/2');
video('even-canvas','修正偶数视频尺寸',()=> 'pad=ceil(iw/2)*2:ceil(ih/2)*2');
video('blackwhite','高对比黑白视频',()=> 'format=gray,eq=contrast=1.35:brightness=-0.05');
video('colorize-warm','视频暖色调',()=> 'colorbalance=rs=.12:gs=.03:bs=-.06');
audio('pan-mono','双声道混合单声道',()=> 'pan=mono|c0=.5*c0+.5*c1');
audio('channelmap-stereo','标准化立体声布局',()=> 'aformat=channel_layouts=stereo');
audio('aformat-s16','标准化 16 位采样',()=> 'aformat=sample_fmts=s16');
audio('stereowiden','扩展立体声宽度',()=> 'stereowiden=delay=20:feedback=0.3:crossfeed=0.3:drymix=0.8');
audio('stereotools','立体声工具调整',()=> 'stereotools=mlev=0.8:slev=1.1:mpan=0');
audio('extrastereo','增强左右声道差异',()=> 'extrastereo=m=1.4:c=0');
audio('earwax','耳机空间化音效',()=> 'earwax');
audio('haas','Haas 空间延迟',()=> 'haas=left_delay=2:right_delay=3:side_gain=0.8');
audio('apulsator','节奏脉冲音量',()=> 'apulsator=hz=2:amount=0.35');
audio('afreqshift','音频频率平移',()=> 'afreqshift=shift=120');
audio('aphaseshift','音频相位平移',()=> 'aphaseshift=shift=0.15');
audio('asoftclip','软削波音频',()=> 'asoftclip=type=tanh:threshold=0.8');
audio('speechnorm','语音动态平滑',()=> 'speechnorm=e=6.25:r=0.0001:l=1');
audio('firequalizer','图形均衡器',()=> 'firequalizer=gain=1');
audio('superequalizer','多段均衡器',()=> 'superequalizer=1b=1:3b=1:5b=0:7b=0:9b=0');
audio('mcompand','多段动态压缩',()=> 'mcompand');
audio('dialoguenhance','增强人声对白',()=> 'dialoguenhance=original=0.4');
audio('loudnorm-dual','双遍响度检测兼容模式',()=> 'loudnorm=I=-14:TP=-1.0:LRA=7:dual_mono=true');
audio('volume-ramp','音量渐变',()=> "volume=0.9:enable='between(t,0,1)'");
audio('aresample-48k','音频交付 48kHz',()=> 'aresample=48000');
audio('volume','调整音频音量',p=>`volume=${n(p,'gain',0.8,0,4)}`);
audio('loudnorm','广播响度归一化',()=> 'loudnorm=I=-16:TP=-1.5:LRA=11');
audio('alimiter','限制音频峰值',()=> 'alimiter=limit=0.9');
audio('acompressor','动态压缩音频',()=> 'acompressor=threshold=0.1:ratio=3');
audio('compand','扩展音频动态范围',()=> 'compand=attacks=0.01:decays=0.1:points=-80/-90|-40/-50|0/0');
audio('agate','音频噪声门',()=> 'agate=threshold=0.02:ratio=2');
audio('highpass','音频高通除低频',p=>`highpass=f=${n(p,'frequency',80,10,10000)}`);
audio('lowpass','音频低通削高频',p=>`lowpass=f=${n(p,'frequency',8000,100,20000)}`);
audio('bandpass','保留指定频带',()=> 'bandpass=f=1000:width_type=h:w=1000');
audio('bandreject','削除指定频带',()=> 'bandreject=f=1000:width_type=h:w=200');
audio('bass','调整低音',p=>`bass=g=${n(p,'gain',3,-20,20)}`);
audio('treble','调整高音',p=>`treble=g=${n(p,'gain',2,-20,20)}`);
audio('equalizer','参数均衡器',()=> 'equalizer=f=1000:t=q:w=1:g=3');
audio('aecho','添加回声',()=> 'aecho=0.8:0.9:60:0.2');
audio('chorus','添加合唱效果',()=> 'chorus=0.5:0.9:50:0.2:0.3:2');
audio('flanger','添加镶边效果',()=> 'flanger=delay=2:depth=2');
audio('aphaser','添加相位效果',()=> 'aphaser=in_gain=0.4');
audio('tremolo','添加振幅颤音',()=> 'tremolo=f=5:d=0.4');
audio('vibrato','添加音高颤音',()=> 'vibrato=f=5:d=0.3');
audio('pitch','改变音高并补偿时长',p=>`aresample=48000,asetrate=48000*${n(p,'factor',1.1,0.5,2)},aresample=48000,atempo=${1/n(p,'factor',1.1,0.5,2)}`);
audio('atempo','改变音频速度保持音高',p=>`atempo=${n(p,'speed',1.2,0.5,2)}`);
audio('areverse','倒放音频',()=> 'areverse');
audio('fade-in','音频淡入',()=> 'afade=t=in:d=0.2');
audio('fade-out','音频淡出',()=> 'afade=t=out:st=0.4:d=0.3');
audio('atrim','截取音频时间片段',p=>`atrim=start=${n(p,'start',0.1,0,86400)}:duration=${n(p,'duration',0.4,0.01,86400)},asetpts=PTS-STARTPTS`);
audio('adelay','添加声道延迟',()=> 'adelay=100:all=1');
audio('apad','音频尾部补静音',()=> 'apad=pad_dur=0.2');
audio('silenceremove','去除音频头部静音',()=> 'silenceremove=start_periods=1:start_duration=0.02:start_threshold=-50dB');
audio('afftdn','频谱音频降噪',()=> 'afftdn=nf=-25');
audio('adeclick','修复音频脉冲杂点',()=> 'adeclick');
audio('adeclip','修复音频削波',()=> 'adeclip');
audio('dcshift','调整音频直流偏移',()=> 'dcshift=shift=0.01');
audio('dynaudnorm','动态音量归一化',()=> 'dynaudnorm=f=100:g=3');
audio('stereo','转换双声道音频',()=> 'aformat=channel_layouts=stereo');
audio('mono','将双声道混合为单声道',()=> 'aformat=channel_layouts=mono');
audio('resample','重采样音频',p=>`aresample=${n(p,'sample_rate',44100,8000,96000)}`);
audio('asetrate','修改采样率与播放节奏',()=> 'asetrate=44100');
audio('anull','音频无损解码导出',()=> 'anull');
audio('asubboost','增强超低频',()=> 'asubboost=dry=0.8:wet=0.2');
audio('crossfeed','耳机跨声道混合',()=> 'aformat=channel_layouts=stereo,crossfeed=strength=0.3');
operations.push(require('./localOcrOperation'));
operations.push(require('./localUpscaleOperation'));
operations.push(require('./localSearchablePdfOperation'));
operations.push(...require('./videoReversePrompt').operations);
operations.push(require('./videoTimelineEdit'));
operations.push(require('./audioBeatAnalysis'));
operations.push(require('./imageCompositeLayers'));
operations.push(require('./videoComposeClips'));
function getOperation(id) { return operations.find(o=>o.id===id); }
function contracts() { return operations.map(o=>({module_id:o.id,title:o.title,description:o.description||o.title,description_zh:o.description_zh||o.title,version:1,version_track:'V5',phase:o.phase||'edit',executor:'local',availability:'bridge',component_id:o.component_id,auto_install:Boolean(o.component_id),
  additional_components:o.additional_components || [],validation_status:verifiedOperation(o.id)?'verified_windows_fixture':'execution_receipt_required',source_refs:[o.source],inputs:o.inputs||['input_path','parameters'],outputs:['derived_media','execution_receipt'],parameters:o.defaults,parameter_schema:o.parameter_schema||parameterSchemas[o.id],
  side_effects:{network:true,filesystem_write:true,database_write:true,external_write:false,paid:false},recovery:'复用同一请求键和原素材；缺组件自动准备；失败只恢复此作业，不重建成功素材'})); }
module.exports={operations,getOperation,contracts};
