const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),vm=require('node:vm');
const bridge=require('../src/services/afterEffectsJob');
function temp(t){const d=fs.mkdtempSync(path.join(os.tmpdir(),'ae-job-'));t.after(()=>fs.rmSync(d,{recursive:true,force:true}));return d;}
const base=()=>({mode:'compose',comps:[{id:'main',width:1280,height:720,duration:2,layers:[{id:'title',type:'text',text:'test'}]}]});
test('job identity preserves output and hostile text remains data',t=>{const d=temp(t),j=base();j.comps[0].layers[0].text='";app.quit();//\n中文';bridge.prepare(j,d);new vm.Script(fs.readFileSync(path.join(d,'ae-job.jsx'),'utf8'));assert.equal(bridge.prepare(j,d).reused,true);assert.throws(()=>bridge.prepare({...j,view_time:1},d),{code:'AE_JOB_CONFLICT'});});
test('invalid source order, key times, cycles and output paths fail before dispatch',()=>{let j=base();j.render={comp:'main',extension:'../evil'};assert.throws(()=>bridge.validate(j));j=base();j.comps[0].layers=[{id:'a',type:'null',parent:'b'},{id:'b',type:'null',parent:'a'}];assert.throws(()=>bridge.validate(j),/cycle/);j=base();j.comps[0].layers[0].properties=[{path:['ADBE Transform Group','ADBE Position'],keys:[{time:1,value:[0,0]},{time:0,value:[2,2]}]}];assert.throws(()=>bridge.validate(j),/increase/);});
test('busy project is not replaced without preservation',t=>{const d=temp(t);bridge.prepare(base(),d);let saved;const mockFile=function(){this.fsName='f';this.open=()=>true;this.write=v=>saved=v;this.close=()=>{};};vm.runInNewContext(fs.readFileSync(path.join(d,'ae-job.jsx'),'utf8'),{app:{version:'test',project:{numItems:1,dirty:true,file:null}},Folder:function(){this.exists=true;this.fsName=d;},File:mockFile});assert.match(JSON.parse(saved).error,/AE_PROJECT_BUSY/);});
test('existing dispatch is reconciled without launching or deleting lock on timeout',async t=>{const d=temp(t);bridge.prepare({mode:'inspect'},d);fs.writeFileSync(path.join(d,'ae-dispatch.json'),'{}');const lock=path.join(d,'lock.json');fs.writeFileSync(lock,JSON.stringify({dir:d}));await assert.rejects(bridge.execute({mode:'inspect'},d,{executable:'missing',timeout:1,lockPath:lock}),{code:'AE_RESULT_UNKNOWN'});assert.ok(fs.existsSync(lock));});
test('actual AE output path supersedes rewritten suffix and requires a real file',t=>{const d=temp(t),p=bridge.prepare({mode:'inspect'},d);const actual=path.join(d,'render.mp4');fs.writeFileSync(actual,'fixture');fs.writeFileSync(path.join(d,'ae-receipt.json'),JSON.stringify({request_sha256:p.request_sha256,status:'rendered_pending_media_qa',outputs:[path.join(d,'render.avi')],output_settings:{'Output File Info':{'Full Flat Path':actual}}}));assert.deepEqual(bridge.read(d).outputs,[actual]);fs.unlinkSync(actual);assert.throws(()=>bridge.read(d),{code:'AE_OUTPUT_MISSING'});});
test('AE registry and source snapshots use the real structured job inputs',t=>{const d=temp(t),asset=path.join(d,'input.png'),input=path.join(d,'job.json');fs.writeFileSync(asset,'fixture');fs.writeFileSync(input,JSON.stringify({mode:'inspect',assets:[{id:'a',path:asset}]}));const sources=require('../src/services/localMediaSources').snapshot({module_id:'local.ae.compose',input_path:input});assert.equal(sources.length,2);assert.ok(require('../src/services/localMediaOperations').getOperation('local.ae.compose').executeNative);});
